name: soranonaka
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  hexcolor: ^3.0.1
  flutter_riverpod: ^2.3.2
  go_router: ^6.2.0
  gap: ^2.0.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  package_info_plus: ^3.0.3
  url_launcher: ^6.1.10
  stylish_bottom_bar: ^1.0.0
  card_swiper: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true